server:
  port: 8080

spring:
  application:
    name: telemetry
  profiles:
    active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/telemetry}
    username: ${SPRING_DATASOURCE_USERNAME:telemetry_user}
    password: ${SPRING_DATASOURCE_PASSWORD:telemetry_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always