name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: telemetry
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (without tests)
        run: ./mvnw clean package -DskipTests

      - name: Run unit & integration tests
        run: ./mvnw test

      - name: Package Docker images
        run: docker compose -f docker-compose.yml build

      - name: Run Docker containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for Spring Boot service to be healthy
        run: |
          echo "Waiting for app to become available..."
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep UP; then
              echo "App is up!"
              exit 0
            fi
            sleep 5
          done
          echo "App failed to start in time."
          docker compose logs
          exit 1

      - name: Stop and clean up containers
        run: docker compose -f docker-compose.yml down

