name: Java CI with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: telemetry
          MYSQL_USER: telemetry_user
          MYSQL_PASSWORD: telemetry_password
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set execute permissions on mvnw
        run: chmod +x ./mvnw

      - name: Wait for MySQL to be healthy
        run: |
          for i in {1..15}; do
            if docker ps --format '{{.Names}} {{.Status}}' | grep -q "healthy"; then
              echo "MySQL is healthy"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Build and run unit tests
        run: ./mvnw clean test

      - name: Package without tests
        run: ./mvnw package -DskipTests

      - name: Build Docker image
        run: docker build -t telemetry-app .