name: Java CI with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: telemetry
          MYSQL_USER: telemetry_user
          MYSQL_PASSWORD: telemetry_password
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set execute permissions on mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven (without tests)
        run: ./mvnw clean package -DskipTests

      - name: Run unit & integration tests
        run: ./mvnw test

      - name: Package Docker images
        run: docker compose -f docker-compose.yaml build

      - name: Run Docker containers
        run: docker compose -f docker-compose.yaml up -d